shared:
    image: node:20

annotations:
    screwdriver.cd/chainPR: true

jobs:
    first-job:
        requires: [ ~pr, ~commit ]
        steps:
            - echo: echo "this is first job."
    second-job:
        requires: [ first-job, detached-job]
        steps:
            - echo: echo "this is second job."
    detached-job:
        steps:
            - echo: echo "this is detached job.   "
